name: are_engine_core
description: "Action Rule Event Engine - Zero dependency, cross-platform, lightweight event-rule-action engine for Dart & Flutter."
version: 1.0.2
homepage: https://github.com/BeratARPA/ARE/tree/master/are_engine_core
repository: https://github.com/BeratARPA/ARE/tree/master/are_engine_core

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.24.0
